version: 0.2

phases:
  install:
    commands:
      - npm install -g yarn
      - yarn install
  pre_build:
    commands:
      - yarn test
  build:
    commands:
      - make
  post_build:
    commands:
      - aws lambda update-function-code --function-name ${AWS_LAMBDA_FUNCTION_NAME} --zip-file fileb://dist/package/lambda-image-file-spoiler.zip --publish
artifacts:
  files:
    - lambda-image-file-spoiler.zip
  discard-paths: yes
  base-directory: dist/package
