version: 0.2

phases:
  install:
    commands:
      - npm install -g yarn
      - yarn install
  pre_build:
    commands:
      - yarn test
  build:
    commands:
      - make
artifacts:
  files:
    - lambda-image-file-spoiler.zip
  discard-paths: yes
  base-directory: dist/package
